import {
    OBSIDIAN_BLOCK_ID_ENDOFLINE_REGEX,
    OBSIDIAN_TAG_AT_STARTOFLINE_REGEX,
    SR_METADATA_CALLOUT as SR_METADATA_CALLOUT,
} from "src/data/constants";
import { DataStore } from "src/data/data-store/base/data-store";
import { DataStoreAlgorithm } from "src/data/data-store/base/data-store-algorithm";
import { Card } from "src/data/data-structures/card/card";
import {
    TopicPath,
    TopicPathList,
    TopicPathWithWs,
} from "src/data/data-structures/deck/topic-path";
import { SRSettings } from "src/data/settings";
import { Note } from "src/note/note";
import { ParsedQuestionInfo } from "src/parser";
import {
    appendCardCommentEntry,
    extractCardCommentRef,
    formatCardCommentRef,
    generateCardCommentLabel,
} from "src/utils/card-comment";
import { collectCardCommentLabels, findFootnoteDefinition } from "src/utils/note-footnotes";
import { cyrb53, MultiLineTextFinder, stringTrimStart, TextDirection } from "src/utils/strings";

export enum CardType {
    SingleLineBasic,
    SingleLineReversed,
    MultiLineBasic,
    MultiLineReversed,
    Cloze,
}

// QuestionText comprises the following components:
//      1. QuestionTopicPath (optional, and if present there may be whitespace before)
//
//      2. Actual question text (mandatory)
//
//      3. Card schedule info as HTML comment (optional). If present then there is
//          optional whitespace after the question text, before this.
//          (whitespace always included when text is generated by formatForNote(), would only
//          be missing if manually removed by the user)
//
//      4. Obsidian block identifier (optional)
//
// Actual Question - Whitespace Handling
//
//      It is important that whitespace is maintained accurately by this class.
//
//      **Leading Whitespace**
//
//          It's important to retain the leading whitespace in the case where there is no QuestionTopicPath,
//          as leading whitespace is an indicator in markdown of the indent level.
//          see "[BUG] Problem with nested list item's indentation"
//          https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/800
//
//          In the case where QuestionTopicPath is present, whitespace pre and post QuestionTopicPath
//          are retained so that if the question is written back to the file, for aesthetic reasons
//          there won't be any change to the whitespace.
//
//          However, actualQuestion will not have any leading spaces.
//
//      **Trailing Whitespace**
//
//         Trailing whitespace is always removed.
//
//         This is because Question.formatForNote() uses the whitespace generated by Question.getHtmlCommentSeparator()
//         as the separator between the end of the question text and the OSR html comment -
//         either a single space or a new line (settings based)
//
// For example
//
//  Actual question text only:
//      Q1::A1
//
//  Question text with topic path:
//      #flashcards/science  Q2::A2
//
//  Question text with card schedule info:
//      #flashcards/science  Q2::A2 <!--SR:!2023-10-16,34,290-->
//
//  Question text with card schedule info and block identifier:
//      #flashcards/science  Q2::A2 <!--SR:!2023-10-16,34,290--> ^d7cee0
//
//  Question text with block identifier:
//      Q2::A2 ^d7cee0
export class QuestionText {
    // Complete text including all components, as read from file
    original: string;

    // The question topic path (only present if topic path included in original text)
    // If present, it also includes whitespace before and after the topic path itself
    topicPathWithWs: TopicPathWithWs;

    // The question text, e.g. "Q1::A1" with leading/trailing whitespace as described above
    actualQuestion: string;

    // Either LTR or RTL
    textDirection: TextDirection;

    // The block identifier (optional), e.g. "^quote-of-the-day"
    // Format of block identifiers:
    //      https://help.obsidian.md/Linking+notes+and+files/Internal+links#Link+to+a+block+in+a+note
    //      Block identifiers can only consist of letters, numbers, and dashes.
    // If present, then first character is "^"
    obsidianBlockId: string;

    // Label of the footnote holding the user's dated notes about this card, e.g. "sr-a3f91c",
    // or null when the card has no comment. Deliberately excluded from textHash.
    cardCommentRef: string | null;

    // Hash of string  (topicPath + actualQuestion)
    // Explicitly excludes the HTML comment with the scheduling info, the obsidian block ID,
    // and the card comment reference
    textHash: string;

    constructor(
        original: string,
        topicPathWithWs: TopicPathWithWs,
        actualQuestion: string,
        textDirection: TextDirection,
        blockId: string,
        cardCommentRef: string | null = null,
    ) {
        this.original = original;
        this.topicPathWithWs = topicPathWithWs;
        this.actualQuestion = actualQuestion;
        this.textDirection = textDirection;
        this.obsidianBlockId = blockId;
        this.cardCommentRef = cardCommentRef;

        // The hash is generated based on the topic and question, explicitly not the schedule or obsidian block ID
        this.textHash = cyrb53(this.formatTopicAndQuestion());
    }

    endsWithCodeBlock(): boolean {
        return this.actualQuestion.endsWith("```");
    }

    static create(
        original: string,
        textDirection: TextDirection,
        settings: SRSettings,
    ): QuestionText {
        const [topicPathWithWs, actualQuestion, blockId, cardCommentRef] = this.splitText(
            original,
            settings,
        );

        return new QuestionText(
            original,
            topicPathWithWs,
            actualQuestion,
            textDirection,
            blockId,
            cardCommentRef,
        );
    }

    static splitText(
        original: string,
        settings: SRSettings,
    ): [TopicPathWithWs | null, string, string, string | null] {
        const originalWithoutSR = DataStore.getInstance().removeScheduleInfo(original);
        let actualQuestion: string = originalWithoutSR.trimEnd();

        let topicPathWithWs: TopicPathWithWs | null = null;

        // originalWithoutSR - [[preTopicPathWs] TopicPath [postTopicPathWs]] Question [whitespace blockId]
        const topicPath = TopicPath.getTopicPathFromCardText(originalWithoutSR);
        if (topicPath?.hasPath) {
            // cardText2 - TopicPath postTopicPathWs Question [whitespace blockId]
            const [preTopicPathWs, cardText2] = stringTrimStart(originalWithoutSR);

            // cardText3 - postTopicPathWs Question [whitespace blockId]
            const cardText3: string = cardText2.replaceAll(OBSIDIAN_TAG_AT_STARTOFLINE_REGEX, "");

            // actualQuestion - Question [whitespace blockId]
            let postTopicPathWs: string;
            [postTopicPathWs, actualQuestion] = stringTrimStart(cardText3);
            // Trailing whitespace must go here too, or endsWithCodeBlock() is false for a
            // tagged card ending in a fence and the schedule is written onto the closing
            // fence, permanently breaking write-back for that card.
            actualQuestion = actualQuestion.trimEnd();
            if (!settings.convertFoldersToDecks) {
                topicPathWithWs = new TopicPathWithWs(topicPath, preTopicPathWs, postTopicPathWs);
            }
        }

        // The line can carry both an Obsidian block id and this plugin's footnote reference,
        // and formatForNote orders them differently in the same-line and own-line cases.
        // Strip whichever matches at the end, repeatedly, so order never matters.
        let blockId: string | null = null;
        let cardCommentRef: string | null = null;
        for (;;) {
            const [withoutBlockId, foundBlockId] = this.extractObsidianBlockId(actualQuestion);
            if (foundBlockId) {
                blockId = foundBlockId;
                actualQuestion = withoutBlockId;
                continue;
            }
            const [withoutRef, foundRef] = extractCardCommentRef(actualQuestion);
            if (foundRef) {
                cardCommentRef = foundRef;
                actualQuestion = withoutRef;
                continue;
            }
            break;
        }

        return [topicPathWithWs, actualQuestion, blockId, cardCommentRef];
    }

    static extractObsidianBlockId(text: string): [string, string] {
        let question: string = text;
        let blockId: string | null = null;
        const match = text.match(OBSIDIAN_BLOCK_ID_ENDOFLINE_REGEX);
        if (match) {
            blockId = match[0].trim();
            const newLength = question.length - blockId.length;
            question = question.substring(0, newLength).trimEnd();
        }

        return [question, blockId];
    }

    formatTopicAndQuestion(): string {
        let result: string = "";
        if (this.topicPathWithWs) {
            result += this.topicPathWithWs.formatWithWs();
        }

        result += this.actualQuestion;
        return result;
    }
}

export class Question {
    note: Note;
    parsedQuestionInfo: ParsedQuestionInfo;
    topicPathList: TopicPathList;
    questionText: QuestionText;
    questionContext: string[];
    cards: Card[];
    hasChanged: boolean;

    // The footnote definition holding this card's comments, as read from the note, or null
    cardCommentDefinition: string | null = null;

    // Staged comment text/date, set by stageCardComment() and consumed by resolveCardComment()
    private pendingCardCommentText: string | null = null;
    private pendingCardCommentDate: string | null = null;

    get questionType(): CardType {
        return this.parsedQuestionInfo.cardType;
    }
    get lineNo(): number {
        return this.parsedQuestionInfo.firstLineNum;
    }

    constructor(init?: Partial<Question>) {
        Object.assign(this, init);
    }

    getHtmlCommentSeparator(settings: SRSettings, hasMetadataCallout: boolean): string {
        const sep: string =
            this.isCardCommentsOnSameLine(settings) || hasMetadataCallout ? " " : "\n";
        return sep;
    }

    /**
     * Appends the comment reference where the schedule comment would have gone. Used on the
     * paths that have no schedule comment to sit in front of, so the reference still inherits
     * the plugin's own same-line/own-line placement decision.
     */
    private appendCardCommentRef(result: string, ref: string, settings: SRSettings): string {
        if (!ref) return result;
        const trimmed: string = result.trimEnd();
        return trimmed + (this.isCardCommentsOnSameLine(settings) ? ` ${ref}` : `\n${ref}`);
    }

    isCardCommentsOnSameLine(settings: SRSettings): boolean {
        let result: boolean = settings.cardCommentOnSameLine;
        // Schedule info must be on next line if last block is a codeblock
        if (this.questionText.endsWithCodeBlock()) {
            result = false;
        }
        return result;
    }

    setCardList(cards: Card[]): void {
        this.cards = cards;
        this.cards.forEach((card) => (card.question = this));
    }

    /** Records the footnote label for this card's comment. */
    setCardCommentRef(label: string): void {
        if (this.questionText.cardCommentRef === label) return;
        this.questionText.cardCommentRef = label;
        this.hasChanged = true;
    }

    /** Records comment text to be written by the next write of this question. */
    stageCardComment(text: string, date: string): void {
        this.pendingCardCommentText = text;
        this.pendingCardCommentDate = date;
        this.hasChanged = true;
    }

    /**
     * Resolves any staged comment against the note's current text: allocates a footnote
     * label if this card has none, and returns the definition to write. Returns null when
     * nothing is staged. Called by the data store, which has already read the note.
     */
    resolveCardComment(noteText: string): string | null {
        const text: string | null = this.pendingCardCommentText;
        const date: string | null = this.pendingCardCommentDate;
        this.pendingCardCommentText = null;
        this.pendingCardCommentDate = null;
        if (!text || !date) return null;

        let label: string | null = this.questionText.cardCommentRef;
        if (!label) {
            label = generateCardCommentLabel(collectCardCommentLabels(noteText));
            this.setCardCommentRef(label);
        }

        const definition: string | null = appendCardCommentEntry(
            this.cardCommentDefinition ?? findFootnoteDefinition(noteText, label),
            label,
            text,
            date,
        );
        return definition;
    }

    formatForNote(settings: SRSettings): string {
        let result: string = this.questionText.formatTopicAndQuestion();
        const blockId: string = this.questionText.obsidianBlockId;
        const ref: string = this.questionText.cardCommentRef
            ? formatCardCommentRef(this.questionText.cardCommentRef)
            : "";
        const hasSchedule: boolean = this.cards.some((card) => card.hasSchedule);
        if (hasSchedule) {
            result = result.trimEnd();

            const scheduleHtml =
                DataStoreAlgorithm.getInstance().questionFormatScheduleAsHtmlComment(this);

            if (scheduleHtml) {
                // Check if the schedule is in the metadata callout and adjust the separator accordingly
                const isScheduleInSRMetadataCallout = result.includes(SR_METADATA_CALLOUT);

                // Add the callout if the schedule is not in the metadata callout
                if (settings.useCalloutsForSchedulingComments && !isScheduleInSRMetadataCallout) {
                    result += `${result.endsWith("\n") ? "" : "\n"}${SR_METADATA_CALLOUT} \n> `;
                }

                // The reference travels immediately before the schedule comment, so it
                // inherits the plugin's own safe placement and can never land inside a
                // code fence or a math block.
                const scheduleFragment: string = ref ? `${ref} ${scheduleHtml}` : scheduleHtml;

                if (blockId) {
                    if (
                        this.isCardCommentsOnSameLine(settings) ||
                        isScheduleInSRMetadataCallout ||
                        settings.useCalloutsForSchedulingComments
                    )
                        result += ` ${scheduleFragment} ${blockId}`;
                    else result += ` ${blockId}\n${scheduleFragment}`;
                } else {
                    result +=
                        this.getHtmlCommentSeparator(
                            settings,
                            isScheduleInSRMetadataCallout ||
                                settings.useCalloutsForSchedulingComments,
                        ) + scheduleFragment;
                }
            } else {
                if (blockId) {
                    result += ` ${blockId}`;
                }
                // A reference must still be emitted here, or it is lost on write-back
                result = this.appendCardCommentRef(result, ref, settings);
            }
        } else {
            // No schedule, so the block ID always comes after the question text
            if (blockId) result += ` ${blockId}`;
            result = this.appendCardCommentRef(result, ref, settings);
        }
        return result;
    }

    updateQuestionWithinNoteText(noteText: string, settings: SRSettings): string {
        const originalText: string = this.questionText.original;

        // Get the entire text for the question including:
        //      1. the topic path (if present),
        //      2. the question text
        //      3. the schedule HTML comment (if present)
        const replacementText = this.formatForNote(settings);

        let newText = MultiLineTextFinder.findAndReplace(noteText, originalText, replacementText);
        if (newText) {
            // Don't support changing the textDirection setting
            this.questionText = QuestionText.create(
                replacementText,
                this.questionText.textDirection,
                settings,
            );
        } else {
            console.warn(
                `updateQuestionText: Text not found: ${originalText.substring(
                    0,
                    100,
                )} in note: ${noteText.substring(0, 100)}`,
            );
            newText = noteText;
        }
        return newText;
    }

    async writeQuestion(settings: SRSettings): Promise<void> {
        const fileText: string = await this.note.file.read();

        const newText: string = this.updateQuestionWithinNoteText(fileText, settings);
        await this.note.file.write(newText);
        this.hasChanged = false;
    }

    formatTopicPathList(): string {
        return this.topicPathList.format("|");
    }

    static Create(
        settings: SRSettings,
        parsedQuestionInfo: ParsedQuestionInfo,
        noteTopicPathList: TopicPathList,
        textDirection: TextDirection,
        context: string[],
    ): Question {
        const questionText: QuestionText = QuestionText.create(
            parsedQuestionInfo.text,
            textDirection,
            settings,
        );

        let topicPathList: TopicPathList = noteTopicPathList;
        if (questionText.topicPathWithWs) {
            topicPathList = new TopicPathList([questionText.topicPathWithWs.topicPath]);
        }

        const result: Question = new Question({
            parsedQuestionInfo,
            topicPathList,
            questionText,
            questionContext: context,
            cards: undefined,
            hasChanged: false,
        });

        return result;
    }
}
